name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint with ESLint
        run: pnpm run lint -- $(git diff --name-only HEAD...${{ github.event.pull_request.base.ref }} | grep '\.c\?js$' | xargs)
